import type { Topic } from "@/lib/types";
export const topics: Topic[] = [
  { slug: "economics", title: "Investment & Markets", description: "Key shifts in markets, consumer demand, competition and economic forces.", introduction: "Markets bring together human expectations and economic reality. These essays look beyond daily price movements to explore business quality, risk, incentives and the patient work of investing.", image: "/images/investment.png", imageAlt: "Growing coin stacks and a small tree alongside an upward investment chart", subtopics: ["Long-term investing", "Economics", "Market cycles", "Behavioural finance"], home: true , href:"/writing/economics/pensions-are-not-fit-for-purpose-reform-is-needed" },
  { slug: "public-policy", title: "Behaviour & Public Health ", description: "Exploring government policies, regulations and societal impact.", introduction: "Technology changes what a business can do, but enduring value still depends on understanding people. Explore entrepreneurship, artificial intelligence and the decisions that help organisations adapt.", image: "/images/business.png", imageAlt: "Business colleagues exchanging a handshake in a bright office", subtopics: ["Entrepreneurship", "Artificial intelligence", "Productivity", "Business models"], home: true , href:"/writing/public-policy/scotland-should-build-on-the-private-sector-role-in-public-health" },
  { slug: "business", title: "Business & Technology", description: "Insights into growth, leadership, innovation and modern business decisions.", introduction: "The choices available to us are shaped by the places we live, the institutions around us and the incentives we face. An economic perspective can help connect individual behaviour with better public health and fairer opportunities.", image: "/images/health.png", imageAlt: "People standing behind a globe and a stethoscope, representing public health", subtopics: ["Population health", "Food policy", "Inequality", "Incentives"], home: true , href:"/writing/business/ai-hitting-the-talent-pipeline-policy-implementation-is-too-slow" },
  { slug: "education", title: "Education & Society  ", description: "Examining changing education models, workforce skills and learning.", introduction: "Education is about more than qualifications. It shapes judgement, widens opportunity and helps people navigate an uncertain world. These perspectives connect learning, financial understanding and the institutions that support a thriving society.", image: "/images/education.png", imageAlt: "A graduation cap on a globe in warm sunlight", subtopics: ["Financial education", "Lifelong learning", "Institutions", "Opportunity"], home: true  , href:"/writing/education/action-needed-on-digital-harms-for-scotlands-young-people"},
  // { slug: "other-interests", title: "Other Interests", description: "Perspectives on technology, society, culture and other developments.", introduction: "Some of the most useful ideas arrive from outside our immediate field. Notes on reading, everyday observation and life in Scotland offer another way into questions about how people and economies work.", image: "/images/listing-banner.png", imageAlt: "Coffee, reading glasses and an open notebook on a desk", subtopics: ["Reading", "Scotland", "Observation", "Decision-making"], home: false , href:"/writing/economics/pensions-are-not-fit-for-purpose-reform-is-needed" },
];
export const getTopic = (slug: string) => topics.find((topic) => topic.slug === slug);
